<Screen1>:
    id: scr1
    orientation: "vertical"
            
    Button:
        id: change_to_1
        pos: (root.width-self.width)/2, 400
        size: 1200, 200
        size_hint: None, None
        text: "Change the text on the 2nd screen to »1st text«"
        on_press: root.functionname()
        
    Button:
        id: change_to_2
        pos: (root.width-self.width)/2, 800
        size: 1200, 200
        size_hint: None, None
        text: "Change the text on the 2nd screen to »2nd text«"
        #on_press: (I don‘t know what should be there)
        
    Button:
        id: go_to_other_screen
        pos: (root.width-self.width)/2, 1400
        size: 600, 200
        size_hint: None, None
        text: "Go to other screen"
        on_press: root.manager.current = "scr2"
        
<Screen2>:
    
    id: scr2
    orientation: "vertical"
            
    Label:
        id: text
        text: "Text which should be changed"
        pos: (root.width-self.width)/2, 800
        size: 600, 200
        
    Button:
        id: go_to_other_screen
        pos: (root.width-self.width)/2, 1400
        size: 600, 200
        size_hint: None, None
        text: "Go to other screen"
        on_press: root.manager.current = "scr1"